### ISSUE TITLE
Data loss when logging

### ISSUE THREAD

**Issue by MathieuJeck** [RohmSemiconductor/RoKiX-IoT-Platform#2]
I work with the KX132-1211 and want to record data using the evalKit.
At 3200Hz sampling rate I observe data loss, see picture.

I tried with the Python CTI but it does not work with the new host board version (2.4), it is still meant to work with the old 2.0 version.
Finding the 2.0 firmware is quite tedious, please update the python scripts as well to work with the newest CY8CKIT-059 firmware version.

I've installed the evalboard environnement following the latest data sheet "No. 62UG085E Rev.004"

Thank you,
Mathieu
![data_bug](https://user-images.githubusercontent.com/37176147/154518446-cec2ba15-da2c-491c-9c53-0b4597c6ebcc.png)

**Comment by MiLaak** [comment]
Hi Mathieu,

Sorry for late reply. Could you double check that you have selected SPI communication from the EVK GUI SW. I2C Communication is not fast enough for high ODRs.
If the problem persists, could you try to update to latest EVK SW which can be downloaded from here https://www.rohm.com/support/accelerometer-evk-support.
